#!/bin/bash

apush() { eval "$1+=(\"\${@:2}\")"; }

needed()
{
    ${OBJDUMP-objdump} --macho --private-headers "$1" |
        {
            declare -a arrays=(load rpath id build vers)
            declare -a load=() rpath=() id=() build=() vers=()
            declare key val rest valtype arry arryv

            while read key val rest; do
                case $key:$val in
                    Load:command      )         valtype=      ;;

                    cmd:LC_ID_DYLIB   )         valtype=id    ;;
                    cmd:LC_RPATH      )         valtype=rpath ;;
                    cmd:LC_LOAD_DYLIB )         valtype=load  ;;
                    cmd:LC_BUILD_VERSION )      valtype=build ;;
                    cmd:LC_VERSION_MIN_MACOSX ) valtype=vers  ;;
                    cmd:*             )         valtype=      ;;

                    name:* | path:* )
                        case $valtype:$key in
                             load:name   ) apush $valtype "$val" ;;

                               id:name   ) apush $valtype "ID    = $val" ;;
                            rpath:path   ) apush $valtype "RPATH = $val" ;;
                        esac ;;

                    sdk:* | minos:* | version:* )
                        case $valtype:$key in
                            vers:sdk     ) apush $valtype "SDK   = $val" ;;
                            vers:version ) apush $valtype "MIN   = $val" ;;

                            build:sdk    ) apush $valtype "SDK   = $val" ;;
                            build:minos  ) apush $valtype "MIN   = $val" ;;
                        esac ;;
                esac
            done

            for arry in "${arrays[@]}"; do
                eval arryv="(\"\${$arry[@]}\")"
                for elt in "${arryv[@]}"; do
                    echo "$elt"
                done
            done
        }
}

main()
{
  case $# in
    0 ) echo "Usage: $0 [files ...]" 1>&2
        exit 1 ;;

    1 ) needed "$1" ;;

    * ) for f in "$@"; do
          echo "$f:"
          needed "$f" | sed -e 's/^/	/'
          echo
        done ;;
  esac
}

main "$@"

# eof
