#!/bin/sh
# $Id: osx-enable-legacy-vnc,v 1.2 2012/05/15 01:01:22 friedman Exp $

/System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart \
    -verbose \
    -activate \
    \
    -configure \
      -access         -on \
      -privs          -all \
      -allowAccessFor -allUsers \
    \
    -clientopts \
      -setmenuextra -menuextra yes \
      -setdirlogins -dirlogins yes \
    \
      -setreqperm   -reqperm   yes \
      -setvnclegacy -vnclegacy yes \
      -setvncpw     -vncpw     "${1-password}" \
      -setwbem      -wbem      yes \
    \
    -restart \
      -agent \
      -console \
      -menu

# eof
