#!/bin/sh
# $Id: osx-boot-flags,v 1.1 2016/10/14 22:14:09 friedman Exp $

# An alternative approach is: /usr/sbin/nvram boot-args="-v"

plb()
{
    /usr/libexec/PlistBuddy -c "$*" /Library/Preferences/SystemConfiguration/com.apple.Boot.plist
}

case $# in
    0 ) plb 'print ":Kernel Flags"' ;;
    * ) plb   'set ":Kernel Flags" '"$*" ;;
esac

# eof
