#!/usr/bin/env perl
# $Id: osx-host-uuid,v 1.2 2017/10/20 22:12:12 friedman Exp $

use strict;

sub getuuid
{
  local $_ = `/usr/sbin/nvram platform-uuid`;
  /(\S+)$/ and $_ = $1;
  s/%([\da-f]{2})/chr(hex($1))/egi;
  $_ = join ("-", unpack ('H8H4H4H4H12', $_));
  return lc $1 if /^00000000-0000-1000-8000-(.*)/;
  return uc $_;
}

print getuuid, "\n";

# eof
