#!/bin/sh
# $Id$

# Disable that horrible "3d" dock in 10.5 (Leopard)

cur=`defaults read com.apple.dock no-glass 2> /dev/null`
case $cur in
  0 | '' ) new=TRUE  ;;
  1 )      new=FALSE ;;
esac

defaults write com.apple.dock no-glass -boolean $new \
 && killall Dock

# eof
