#!/bin/sh
# $Id$

# Good resolutions:
#
#     1024x768x32
#     1280x960x32
#     1280x1024x32
#     1400x1050x32
#     1600x1200x32

domain=/Library/Preferences/SystemConfiguration/com.apple.Boot
key='Graphics Mode'
val=$1

defaults write "$domain" "$key" -string "$val" \
  && plutil -convert xml1 "$domain".plist

# eof
