#!/bin/sh
# $Id: osx-toggle-dock-shelf,v 1.1 2008/12/03 01:34:54 friedman Exp $

# Disable that horrible "3d" dock in 10.5 (Leopard)

pref-set-boolean com.apple.dock no-glass "$@" \
    && killall Dock 2> /dev/null

# eof
